version: "3.8"

services:
  cook-book-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
